### ISSUE TITLE
Extract and integrate mindmap functionality as a package

### ISSUE THREAD

**Issue by jordanpartridge** [jordanpartridge/project-api#59]
## Overview
Need to extract the mindmap functionality into a reusable package and integrate it with project-api.

## Current State
- Mind commands in project-api
- Full implementation in mindmap repo
- Duplicate functionality needs consolidation

## Implementation Steps

1. Create mindmap-core Package
- [ ] Set up new repository
- [ ] Extract core models and migrations
- [ ] Create service provider
- [ ] Set up tests

2. Package Development
- [ ] Move Entity model
- [ ] Move Observation model
- [ ] Create GraphService
- [ ] Add Filament resources
- [ ] Set up GitHub Actions

3. Project Integration
- [ ] Add package to project-api
- [ ] Update existing commands
- [ ] Migrate data
- [ ] Update tests

## Technical Requirements
- PHP 8.2+
- Laravel 10/11 compatibility
- Filament 3.x support
- PHPStan level 8+

## Testing Strategy
1. Package tests
2. Integration tests
3. End-to-end command tests
4. Migration tests

## Documentation Needs
1. Package README
2. Integration guide
3. API documentation
4. Migration guide
